name: Tag and publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Name of version'
      name: 
        description: 'Name of image'
        required: true
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
      platforms:
        description: 'List of platforms (JSON)'
        required: false
        default: '["linux/amd64","linux/arm64"]'

jobs:
  build: 
    name: Build and push
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
    runs-on: ${{matrix.platform == 'linux/amd64' && 'ubuntu-latest' || matrix.platform == 'linux/arm64' && fromJson('["self-hosted", "linux", "ARM64"]') || fromJSON('Bad platform') }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/teidesu/${{ inputs.name }}:${{ inputs.version || github.sha }}, ghcr.io/teidesu/${{ inputs.name }}:latest
          push: true
          provenance: false